- name: Pull client data to Ansible server
  hosts: all
  remote_user: semaphore
  become: true
  become_user: root
  vars:
  vars:
    ansible_shell_executable: /bin/bash
    ansible_ssh_private_key_file: /home/semaphore/.ssh/id_semaphore

  tasks:
    - name: Ensure rsync is installed on client
      package:
        name: rsync
        state: present

    - name: Ensure backup directory exists on controller
      file:
        path: "/backups/{{ inventory_hostname }}"
        state: directory
        mode: '0755'
      delegate_to: localhost

    - name: Pull client web data
      ansible.posix.synchronize:
        src: /var/www/client/
        dest: "/backups/{{ inventory_hostname }}/"
        archive: yes
        delete: yes
        compress: yes
        mode: pull
      delegate_to: localhost

    - name: Pull client database data
      ansible.posix.synchronize:
        src: /var/lib/mysql/prestashop/
        dest: "/backups/{{ inventory_hostname }}/data-base/"
        archive: yes
        delete: yes
        compress: yes
        mode: pull
      delegate_to: localhost
