---
- name: Configure Windows Server 2019 as Domain Controller with DNS and DHCP
  hosts: SVR-2019
  gather_facts: yes
  tasks:
    - name: Authorize DHCP server in AD
    
  vars:
    domain_name: activenetware.local
    safe_mode_password: "Web123!!!"
    dhcp_scope_name: "TestScope"
    dhcp_start_ip: "192.168.0.100"
    dhcp_end_ip: "192.168.0.199"
    dhcp_subnet_mask: "255.255.255.0"
    dhcp_gateway: "192.168.0.190"
    dhcp_dns_server: "192.168.0.171"

  tasks:
    - name: Install AD-Domain-Services and DNS roles
      win_feature:
        name:
          - AD-Domain-Services
          - DNS
        state: present
        include_management_tools: yes

    - name: Promote server to Domain Controller
      win_domain:
        dns_domain_name: "{{ domain_name }}"
        safe_mode_password: "{{ safe_mode_password }}"
        domain_netbios_name: ACTIVENETWARE
        reboot: yes

    - name: Wait for server to reboot
      win_reboot:
        reboot_timeout: 600
        test_command: whoami

    - name: Install DHCP Server role
      win_feature:
        name: DHCP
        state: present
        include_management_tools: yes

    - name: Authorize DHCP server in AD
      win_shell: |
        Add-DhcpServerInDC -DnsName "{{ ansible_hostname }}" -IPAddress "{{ dhcp_dns_server }}"

    - name: Create DHCP scope
      win_shell: |
        Add-DhcpServerv4Scope -Name "{{ dhcp_scope_name }}" `
                              -StartRange "{{ dhcp_start_ip }}" `
                              -EndRange "{{ dhcp_end_ip }}" `
                              -SubnetMask "{{ dhcp_subnet_mask }}" `
                              -State Active

    - name: Set DHCP options
      win_shell: |
        Set-DhcpServerv4OptionValue -ScopeId "{{ dhcp_gateway }}" `
                                    -Router "{{ dhcp_gateway }}" `
                                    -DnsServer "{{ dhcp_dns_server }}" `
                                    -DnsDomain "{{ domain_name }}"
